//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.PDM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCOM.PDM.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string AccelerationText {
            get {
                return ResourceManager.GetString("AccelerationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Home.
        /// </summary>
        internal static string AtHomeText {
            get {
                return ResourceManager.GetString("AtHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Park.
        /// </summary>
        internal static string AtParkText {
            get {
                return ResourceManager.GetString("AtParkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Find Home.
        /// </summary>
        internal static string CanFindHomeText {
            get {
                return ResourceManager.GetString("CanFindHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Park.
        /// </summary>
        internal static string CanParkText {
            get {
                return ResourceManager.GetString("CanParkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Set Altitude.
        /// </summary>
        internal static string CanSetAltitudeText {
            get {
                return ResourceManager.GetString("CanSetAltitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Set Azimuth.
        /// </summary>
        internal static string CanSetAzimuthText {
            get {
                return ResourceManager.GetString("CanSetAzimuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Set Park.
        /// </summary>
        internal static string CanSetParkText {
            get {
                return ResourceManager.GetString("CanSetParkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Set Shutter.
        /// </summary>
        internal static string CanSetShutterText {
            get {
                return ResourceManager.GetString("CanSetShutterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Sync Azimuth.
        /// </summary>
        internal static string CanSyncAzimuthText {
            get {
                return ResourceManager.GetString("CanSyncAzimuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities.
        /// </summary>
        internal static string CapabilitiesText {
            get {
                return ResourceManager.GetString("CapabilitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseFormText {
            get {
                return ResourceManager.GetString("CloseFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseShutterText {
            get {
                return ResourceManager.GetString("CloseShutterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutOff.
        /// </summary>
        internal static string CutOffText {
            get {
                return ResourceManager.GetString("CutOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        internal static string DoCalibrateText {
            get {
                return ResourceManager.GetString("DoCalibrateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NexDome Driver version.
        /// </summary>
        internal static string DriverVersionText {
            get {
                return ResourceManager.GetString("DriverVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Turn.
        /// </summary>
        internal static string FullTurnText {
            get {
                return ResourceManager.GetString("FullTurnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string GoHomeText {
            get {
                return ResourceManager.GetString("GoHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        internal static string GoParkText {
            get {
                return ResourceManager.GetString("GoParkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Az.
        /// </summary>
        internal static string GoToAzText {
            get {
                return ResourceManager.GetString("GoToAzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Pos.
        /// </summary>
        internal static string GoToPosText {
            get {
                return ResourceManager.GetString("GoToPosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Homed.
        /// </summary>
        internal static string HasHomedText {
            get {
                return ResourceManager.GetString("HasHomedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home and Park.
        /// </summary>
        internal static string HomeAndParkText {
            get {
                return ResourceManager.GetString("HomeAndParkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Status.
        /// </summary>
        internal static string HomeStatusText {
            get {
                return ResourceManager.GetString("HomeStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number.
        /// </summary>
        internal static string InvalidNumberText {
            get {
                return ResourceManager.GetString("InvalidNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LowText {
            get {
                return ResourceManager.GetString("LowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Speed.
        /// </summary>
        internal static string MaxSpeedText {
            get {
                return ResourceManager.GetString("MaxSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Settings.
        /// </summary>
        internal static string MotorSettingsText {
            get {
                return ResourceManager.GetString("MotorSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        internal static string MovementText {
            get {
                return ResourceManager.GetString("MovementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Homed.
        /// </summary>
        internal static string NeverHomedText {
            get {
                return ResourceManager.GetString("NeverHomedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenShutterText {
            get {
                return ResourceManager.GetString("OpenShutterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        internal static string ParkText {
            get {
                return ResourceManager.GetString("ParkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain Settings.
        /// </summary>
        internal static string RainBoxTitle {
            get {
                return ResourceManager.GetString("RainBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string RainIntervalText {
            get {
                return ResourceManager.GetString("RainIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require twice.
        /// </summary>
        internal static string RainRequireTwiceText {
            get {
                return ResourceManager.GetString("RainRequireTwiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not raining.
        /// </summary>
        internal static string RainStateNotRainingText {
            get {
                return ResourceManager.GetString("RainStateNotRainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAINING.
        /// </summary>
        internal static string RainStateRainingText {
            get {
                return ResourceManager.GetString("RainStateRainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed.
        /// </summary>
        internal static string ReversedText {
            get {
                return ResourceManager.GetString("ReversedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotator.
        /// </summary>
        internal static string RotatorText {
            get {
                return ResourceManager.GetString("RotatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotator version.
        /// </summary>
        internal static string RotatorVersionText {
            get {
                return ResourceManager.GetString("RotatorVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Home.
        /// </summary>
        internal static string SeekHomeText {
            get {
                return ResourceManager.GetString("SeekHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Dome.
        /// </summary>
        internal static string SeekMeasuring {
            get {
                return ResourceManager.GetString("SeekMeasuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Mode.
        /// </summary>
        internal static string SeekModeText {
            get {
                return ResourceManager.GetString("SeekModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move off Home.
        /// </summary>
        internal static string SeekMoveOff {
            get {
                return ResourceManager.GetString("SeekMoveOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SeekNoneText {
            get {
                return ResourceManager.GetString("SeekNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ShutterClosedText {
            get {
                return ResourceManager.GetString("ShutterClosedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close when low.
        /// </summary>
        internal static string ShutterCloseLowText {
            get {
                return ResourceManager.GetString("ShutterCloseLowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string ShutterClosingText {
            get {
                return ResourceManager.GetString("ShutterClosingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        internal static string ShutterOpeningText {
            get {
                return ResourceManager.GetString("ShutterOpeningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ShutterOpenText {
            get {
                return ResourceManager.GetString("ShutterOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter.
        /// </summary>
        internal static string ShutterText {
            get {
                return ResourceManager.GetString("ShutterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ShutterUnknownText {
            get {
                return ResourceManager.GetString("ShutterUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Version.
        /// </summary>
        internal static string ShutterVersionText {
            get {
                return ResourceManager.GetString("ShutterVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps Per.
        /// </summary>
        internal static string StepPerText {
            get {
                return ResourceManager.GetString("StepPerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Az.
        /// </summary>
        internal static string SyncAzText {
            get {
                return ResourceManager.GetString("SyncAzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltages.
        /// </summary>
        internal static string VoltagesBoxTitle {
            get {
                return ResourceManager.GetString("VoltagesBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string VoltageText {
            get {
                return ResourceManager.GetString("VoltageText", resourceCulture);
            }
        }
    }
}
